### What is Data Inspection?

Data inspection is the process of examining the `custumer.csv` dataset to understand its structure, contents, data types, distributions, and potential problems before performing data analysis or machine learning.

Real-world example:

A telecom company receives customer records via `custumer.csv` containing:

* Customer ID
* Age
* Contract type
* Monthly charges
* Internet service
* Churn status

Before building a churn prediction model, we need to inspect the data and answer questions such as:

* How many customers are there?
* Which columns are numerical?
* Which are categorical?
* Are there missing values?
* What values occur in each categorical column?

In [1]:
import pandas as pd

df = pd.read_csv("custumer.csv")
df.head()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.10,2394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.50,3796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

### 1. Number of Rows

The number of rows represents the number of customer records or observations in `custumer.csv`.

In this dataset, each row represents one distinct customer.

Real-world example:

If a telecom company maintains records for 5,020 customers, `custumer.csv` will contain 5,020 rows.

#### AI/ML usage

The number of observations affects:

* Model training
* Model accuracy
* Statistical reliability
* Train/test splitting

More useful observations generally give an ML model more information to learn from.

In [3]:
print("Number of rows in custumer.csv:", len(df))

Number of rows in custumer.csv: 5020

### 2. Number of Columns

The number of columns represents the number of variables or customer attributes present in `custumer.csv`.

Real-world example:

For each customer in `custumer.csv`, we track:

* Age
* Gender
* Monthly charges
* Contract type
* Internet service
* Churn

Each attribute is mapped to a single column.

#### AI/ML usage

Columns usually become features used by an ML model.

In [4]:
print("Number of columns in custumer.csv:", len(df.columns))

Number of columns in custumer.csv: 14

In [5]:
print("Available columns:", df.columns.tolist())

Available columns: ['CustomerID', 'Age', 'Gender', 'TenureYears', 'MonthlyCharges', 'TotalCharges', 'ContractType', 'InternetService', 'PaymentMethod', 'SeniorCitizen', 'SupportCalls', 'StreamingService', 'PaperlessBilling', 'Churn']

### 3. DataTypes

A data type defines how values are stored and interpreted in each column of `custumer.csv`.

Common types include:

| Data Type  | Meaning                       | Example      |
| ---------- | ----------------------------- | ------------ |
| `int64`    | Integer                       | 5, 10, 20    |
| `float64`  | Decimal number                | 25.5, 100.75 |
| `object`   | Usually text/categorical data | Male, Female |
| `datetime` | Date/time                     | 2026-08-24   |

#### AI/ML usage

Data types determine what preprocessing steps (such as encoding or scaling) are required for `custumer.csv`.

In [8]:
df.dtypes

CustomerID           object
Age                 float64
Gender               object
TenureYears           int64
MonthlyCharges      float64
TotalCharges        float64
ContractType         object
InternetService      object
PaymentMethod        object
SeniorCitizen        object
SupportCalls          int64
StreamingService     object
PaperlessBilling     object
Churn                object
dtype: object

### 4. Index

An index identifies the position of each row inside the `custumer.csv` DataFrame.

By default, Pandas assigns an integer RangeIndex starting from 0.

Real-world example:

The index acts as an internal row reference:

Index     CustomerID
0         CUST00001
1         CUST00002
2         CUST00003

#### AI/ML usage

The index is positional metadata and is not used as a predictive feature for churn classification.

In [9]:
print(df.index)

RangeIndex(start=0, stop=5020, step=1)

In [10]:
# Inspecting the first 10 index positions
print(df.index[:10])

RangeIndex(start=0, stop=10, step=1)

In [11]:
# Accessing the very first customer record in custumer.csv
print(df.loc[0])

CustomerID              CUST00001
Age                          56.0
Gender                     Female
TenureYears                     0
MonthlyCharges              20.41
TotalCharges               131.92
ContractType             One year
InternetService               DSL
PaymentMethod       Bank transfer
SeniorCitizen                  No
SupportCalls                    3
StreamingService               No
PaperlessBilling              Yes
Churn                         Yes
Name: 0, dtype: object

### 5. head()

The `head()` method displays the top rows of `custumer.csv` (first 5 by default).

Why use it?

It helps us quickly verify:

* Correct column parsing
* Sample customer records
* Data layout integrity
* Successful loading of `custumer.csv`

In [13]:
df.head()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.10,2394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.50,3796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

In [14]:
df.head(10)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.10,2394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.50,3796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes
5,CUST00006,25.0,Male,5,90.88,5818.04,Two year,DSL,Mailed check,No,0,No,No,No
6,CUST00007,38.0,Female,5,37.79,2670.55,Month-to-month,DSL,Mailed check,No,1,Yes,Yes,No
7,CUST00008,56.0,Male,0,108.85,1106.71,Two year,No,Electronic check,No,4,Yes,No,Yes
8,CUST00009,36.0,Male,9,64.19,7652.76,One year,DSL,Mailed check,No,3,Yes,No,No
9,CUST00010,40.0,Male,1,34.28,618.59,One year,Fiber optic,Electronic check,No,3,Yes,Yes,No

### 6. tail()

The `tail()` method displays the final rows of `custumer.csv`.

Why use it?

It verifies that:

* `custumer.csv` was completely loaded without truncation
* End records match expected structure
* There are no corrupted footer rows

In [15]:
df.tail()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
5015,CUST05016,29.0,Male,9,53.60,5781.23,Two year,Fiber optic,Credit card,Yes,1,No,No,No
5016,CUST05017,20.0,Female,7,96.94,8022.63,Month-to-month,Fiber optic,Electronic check,No,0,No,No,No
5017,CUST05018,34.0,Male,7,46.53,4001.60,Two year,DSL,Electronic check,No,2,No,No,No
5018,CUST05019,47.0,Female,7,109.14,8864.10,Month-to-month,DSL,Credit card,No,1,Yes,No,No
5019,CUST05020,62.0,Male,9,27.16,2885.52,Month-to-month,Fiber optic,Credit card,No,3,No,Yes,No

In [16]:
df.tail(10)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
5010,CUST05011,26.0,Male,6,94.55,6666.31,One year,DSL,Mailed check,No,2,Yes,Yes,No
5011,CUST05012,54.0,Female,1,64.64,793.61,One year,DSL,Electronic check,No,0,Yes,Yes,No
5012,CUST05013,45.0,Female,4,87.85,4284.55,Month-to-month,Fiber optic,Electronic check,No,1,Yes,Yes,No
5013,CUST05014,50.0,Female,1,105.22,1417.07,Month-to-month,No,Electronic check,No,1,No,Yes,No
5014,CUST05015,28.0,Female,6,73.57,5089.45,Month-to-month,DSL,Mailed check,No,0,No,Yes,No
5015,CUST05016,29.0,Male,9,53.60,5781.23,Two year,Fiber optic,Credit card,Yes,1,No,No,No
5016,CUST05017,20.0,Female,7,96.94,8022.63,Month-to-month,Fiber optic,Electronic check,No,0,No,No,No
5017,CUST05018,34.0,Male,7,46.53,4001.60,Two year,DSL,Electronic check,No,2,No,No,No
5018,CUST05019,47.0,Female,7,109.14,8864.10,Month-to-month,DSL,Credit card,No,1,Yes,No,No
5019,CUST05020,62.0,Male,9,27.16,2885.52,Month-to-month,Fiber optic,Credit card,No,3,No,Yes,No

### 7. sample()

`sample()` randomly extracts rows from `custumer.csv`.

#### AI/ML usage

Random sampling is used to:

* Inspect customer variety across different tenure and charge ranges
* Spot unexpected anomalies or edge cases
* Verify broad representative behavior

In [17]:
# Random single record
df.sample()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
5019,CUST05020,62.0,Male,9,27.16,2885.52,Month-to-month,Fiber optic,Credit card,No,3,No,Yes,No

In [18]:
# Random sample of 5 customer records
df.sample(5)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
4008,CUST04009,53.0,Female,5,85.50,5373.18,Month-to-month,Fiber optic,Mailed check,No,1,Yes,No,No
1163,CUST01164,56.0,Female,2,55.50,1447.58,Month-to-month,No,Electronic check,No,2,Yes,Yes,No
4951,CUST04952,21.0,Female,3,22.88,763.71,Month-to-month,Fiber optic,Credit card,No,4,No,Yes,No
1064,CUST01065,39.0,Male,1,50.15,487.57,One year,DSL,Mailed check,No,1,Yes,No,Yes
4816,CUST04817,64.0,Female,5,60.49,3780.73,One year,Fiber optic,Mailed check,No,3,No,Yes,Yes

In [19]:
# Reproducible sample of 5 customers
df.sample(5, random_state=42)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
1504,CUST01505,37.0,Male,1,102.31,1404.56,Two year,DSL,Electronic check,No,2,No,No,No
538,CUST00539,41.0,Male,4,88.81,4182.02,One year,DSL,Mailed check,No,3,Yes,Yes,Yes
3551,CUST03552,25.0,Male,5,45.30,2626.96,Two year,Fiber optic,Bank transfer,Yes,6,No,No,Yes
4945,CUST04946,66.0,Female,5,51.01,3189.16,Month-to-month,Fiber optic,Credit card,No,2,No,No,No
4817,CUST04818,60.0,Male,1,118.14,1765.19,Month-to-month,Fiber optic,Electronic check,No,4,No,Yes,No

### 8. shape

`shape` returns the exact dimensions of `custumer.csv` as `(rows, columns)`.

#### AI/ML usage

Tracks dataset dimensions before and after cleaning steps like dropna or feature addition.

In [21]:
print("custumer.csv dimensions:", df.shape)

custumer.csv dimensions: (5020, 14)

This indicates `custumer.csv` contains 5,020 rows and 14 feature columns.

### 9. info()

`info()` provides a technical summary of `custumer.csv`, detailing:

* Record count
* Feature column names
* Non-null counts (detecting missing values)
* Memory consumption

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5020 entries, 0 to 5019
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        5020 non-null   object
 1   Age               4969 non-null   float64
 2   Gender            5020 non-null   object
 3   TenureYears       5020 non-null   int64
 4   MonthlyCharges    4970 non-null   float64
 5   TotalCharges      4969 non-null   float64
 6   ContractType      5020 non-null   object
 7   InternetService   5020 non-null   object
 8   PaymentMethod     5020 non-null   object
 9   SeniorCitizen     5020 non-null   object
 10  SupportCalls      5020 non-null   int64
 11  StreamingService  5020 non-null   object
 12  PaperlessBilling  5020 non-null   object
 13  Churn             5020 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 549.2+ KB

### 10. describe()

`describe()` computes summary statistics for numerical features in `custumer.csv`.

| Statistic | Meaning                   |
| --------- | ------------------------- |
| count     | Number of non-null values |
| mean      | Average                   |
| std       | Standard deviation        |
| min       | Minimum                   |
| 25%       | First quartile            |
| 50%       | Median                    |
| 75%       | Third quartile            |
| max       | Maximum                   |

In [24]:
df.describe()

               Age  TenureYears  MonthlyCharges  TotalCharges  SupportCalls
count  4969.000000  5020.000000     4970.000000   4969.000000   5020.000000
mean     43.328034     4.911753       69.480559   4126.251849      2.105777
std      14.762282     3.137479       28.678515   3237.099088      1.630602
min      18.000000     0.000000       20.020000     72.450000      0.000000
25%      31.000000     2.000000       44.602500   1440.880000      1.000000
50%      43.000000     5.000000       69.285000   3355.920000      2.000000
75%      56.000000     8.000000       93.770000   6068.800000      3.000000
max      69.000000    10.000000      119.970000  14603.300000      9.000000

### 11. dtypes

Checks individual column storage formats across `custumer.csv`.

In [25]:
df.dtypes

CustomerID           object
Age                 float64
Gender               object
TenureYears           int64
MonthlyCharges      float64
TotalCharges        float64
ContractType         object
InternetService      object
PaymentMethod        object
SeniorCitizen        object
SupportCalls          int64
StreamingService     object
PaperlessBilling     object
Churn                object
dtype: object

### 12. nunique()

`nunique()` counts unique entries per column in `custumer.csv` to flag high-cardinality identifiers versus low-cardinality categorical attributes.

In [28]:
print(df.nunique())

CustomerID          5020
Age                   52
Gender                 2
TenureYears           11
MonthlyCharges      3884
TotalCharges        4953
ContractType           3
InternetService        3
PaymentMethod          4
SeniorCitizen          2
SupportCalls          10
StreamingService       2
PaperlessBilling       2
Churn                  2
dtype: int64

### 13. value_counts()

Counts category frequencies across discrete/categorical variables in `custumer.csv`.

| Contract Type  | Simulated Distribution |
| -------------- | ---------------------- |
| Month-to-month | High frequency         |
| One year       | Medium frequency       |
| Two year       | Medium frequency       |

In [30]:
# Gender breakdown in custumer.csv
df["Gender"].value_counts()

Gender
Male      2587
Female    2433
Name: count, dtype: int64

In [31]:
# Target variable distribution
df["Churn"].value_counts()

Churn
No     3565
Yes    1455
Name: count, dtype: int64

### 14. Numerical Columns

Numerical features in `custumer.csv` allow mathematical and statistical computations.

In [32]:
numerical_columns = df.select_dtypes(include="number").columns
print("Numerical features in custumer.csv:", numerical_columns)

Numerical features in custumer.csv: Index(['Age', 'TenureYears', 'MonthlyCharges', 'TotalCharges', 'SupportCalls'], dtype='object')

### 15. Categorical Columns

Categorical features in `custumer.csv` contain group labels requiring encoding prior to modeling.

In [33]:
categorical_columns = df.select_dtypes(include="object").columns
print("Categorical features in custumer.csv:", categorical_columns)

Categorical features in custumer.csv: Index(['CustomerID', 'Gender', 'ContractType', 'InternetService',
       'PaymentMethod', 'SeniorCitizen', 'StreamingService',
       'PaperlessBilling', 'Churn'],
      dtype='object')

### 16. Feature Engineering: Grouping Continuous Data

Binning `TenureYears` in `custumer.csv` creates a structured categorical feature `TenureGroup`.

In [34]:
df["TenureGroup"] = pd.cut(
    df["TenureYears"],
    bins=[0, 2, 5, 10, float("inf")],
    labels=["0-2 Years", "3-5 Years", "6-10 Years", "10+ Years"],
)

df[["CustomerID", "TenureYears", "TenureGroup"]].head()

  CustomerID  TenureYears TenureGroup
0  CUST00001            0         NaN
1  CUST00002            9  6-10 Years
2  CUST00003            3   3-5 Years
3  CUST00004            8  6-10 Years
4  CUST00005            9  6-10 Years

### 17. Identifier Columns

`CustomerID` uniquely distinguishes each entry in `custumer.csv` and is dropped from feature matrices to avoid overfitting.

In [35]:
df["CustomerID"].head()

0    CUST00001
1    CUST00002
2    CUST00003
3    CUST00004
4    CUST00005
Name: CustomerID, dtype: object

### 18. Target Variable (`Churn`)

`Churn` represents the final label $y$ in `custumer.csv` to be predicted using input features $X$.

In [36]:
df["Churn"].value_counts(normalize=True) * 100

Churn
No     71.015936
Yes    28.984064
Name: proportion, dtype: float64